package org.changppo.cost_management_service.exception.common;

import lombok.Getter;
import org.springframework.http.HttpStatus;

import static org.springframework.http.HttpStatus.*;

@Getter
public enum ExceptionType {
    EXCEPTION(INTERNAL_SERVER_ERROR, "EXCEPTION.CODE", "EXCEPTION.MSG"),
    AUTHENTICATION_ENTRY_POINT_EXCEPTION(UNAUTHORIZED, "AUTHENTICATION_ENTRY_POINT_EXCEPTION.CODE", "AUTHENTICATION_ENTRY_POINT_EXCEPTION.MSG"),
    ACCESS_DENIED_EXCEPTION(FORBIDDEN, "ACCESS_DENIED_EXCEPTION.CODE", "ACCESS_DENIED_EXCEPTION.MSG"),
    BIND_EXCEPTION(BAD_REQUEST, "BIND_EXCEPTION.CODE", "BIND_EXCEPTION.MSG"),
    KAKAO_LOGIN_OAUTH2_FAILURE_EXCEPTION(UNAUTHORIZED, "KAKAO_LOGIN_OAUTH2_FAILURE_EXCEPTION.CODE", "KAKAO_LOGIN_OAUTH2_FAILURE_EXCEPTION.MSG"),
    MEMBER_NOT_FOUND_EXCEPTION(NOT_FOUND, "MEMBER_NOT_FOUND_EXCEPTION.CODE", "MEMBER_NOT_FOUND_EXCEPTION.MSG"),
    MEMBER_DELETE_FAILURE_EXCEPTION(INTERNAL_SERVER_ERROR, "MEMBER_DELETE_FAILURE_EXCEPTION.CODE", "MEMBER_DELETE_FAILURE_EXCEPTION.MSG"),
    KAKAO_OAUTH2_UNLINK_FAILURE_EXCEPTION(INTERNAL_SERVER_ERROR, "KAKAO_OAUTH2_UNLINK_FAILURE_EXCEPTION.CODE", "KAKAO_OAUTH2_UNLINK_FAILURE_EXCEPTION.MSG"),
    ROLE_NOT_FOUND_EXCEPTION(NOT_FOUND, "ROLE_NOT_FOUND_EXCEPTION.CODE", "ROLE_NOT_FOUND_EXCEPTION.MSG"),
    GRADE_NOT_FOUND_EXCEPTION(NOT_FOUND, "GRADE_NOT_FOUND_EXCEPTION.CODE", "GRADE_NOT_FOUND_EXCEPTION.MSG"),
    APIKEY_NOT_FOUND_EXCEPTION(NOT_FOUND, "APIKEY_NOT_FOUND_EXCEPTION.CODE", "APIKEY_NOT_FOUND_EXCEPTION.MSG"),
    PAYMENT_GATEWAY_NOT_FOUND_EXCEPTION(NOT_FOUND, "PAYMENT_GATEWAY_NOT_FOUND_EXCEPTION.CODE", "PAYMENT_GATEWAY_NOT_FOUND_EXCEPTION.MSG"),
    CARD_NOT_FOUND_EXCEPTION(NOT_FOUND, "CARD_NOT_FOUND_EXCEPTION.CODE", "CARD_NOT_FOUND_EXCEPTION.MSG"),
    CARD_REGISTER_FAILURE_EXCEPTION(INTERNAL_SERVER_ERROR, "CARD_REGISTER_FAILURE_EXCEPTION.CODE", "CARD_REGISTER_FAILURE_EXCEPTION.MSG");

    private final HttpStatus status;
    private final String code;
    private final String message;

    ExceptionType(HttpStatus status, String code, String message) {
        this.status = status;
        this.code = code;
        this.message = message;
    }
}